### ISSUE TITLE
Generic URID retrieval

### ISSUE THREAD

**Issue by Janonard** [RustAudio/rust-lv2#21]
This discussion has moved from PR #16. Full discussion as follows:

@prokopyl [(original post)](https://github.com/RustAudio/rust-lv2/pull/16#issuecomment-526834967)
> I know this PR isn't ready for review, but I noticed you pushed b12dd72 on master, and I was wondering what it was useful for until I realized that when implementing the urid URIDCache trait we completely forgot to also bring back the URIDCacheMapping trait implementation! Which is why it is so awkward to use right now. ^^'
>
> Right now the URIDBound ties an URI-bound type to a specific container type, which defeats the most of the point of having an user-customizable URID cache.
>
>The URIDCacheMapping used to work the other way around: it was auto-derived when deriving URIDCache, and it allowed to get the wanted URID with a generic function: my_cache.get_urid::<T>() -> URID<T>, without having to access the fields directly in a way or another, which was very useful for both implementing and using all of the Atom types (which are normally only bound to an URI, not a specific URID cache).
>
> I can make a new PR for this so you can get all the details and explanations, and help you rebase this branch on it later if you'd like. slightly_smiling_face

@Janonard [(original post)](https://github.com/RustAudio/rust-lv2/pull/16#issuecomment-526920973)
> I generally like the idea of the `URIDBound` since it makes generic methods with URIDs easier to write. For example:
>``` Rust
>fn write_urid<T: URIDBound>(target: &mut u32, cache: &T::CacheType) {
>    *target = T::urid(cache).get();
>}
>```
>
> This is very handy indeed!
> 
> Also, using pre-defined URID caches does not conflict with having user-defined caches, it even supports them! Take a look at the setting for the literal test:
> ``` Rust
> struct German;
> 
> unsafe impl UriBound for German {
>     const URI: &'static [u8] = b"http://lexvo.org/id/iso639-1/de\0";
> }
> 
> #[derive(URIDCache)]
> pub struct TestURIDs {
>     atom: AtomURIDCache,
>     german: URID<German>,
> }
> ```
> Here, we have a case where a URID cache is needed that contains both the URIDs for the atom library and other, custom URIDs. We can simply include that pre-defined cache in our own cache and use it! We don't have to care which URIDs are included or have to update our cache every time a new update for the library comes in.
> 
> I guess you thought that specifying a pre-defined URID cache for a URI bound would require a user to always use this specific cache, but as you can see it doesn't! :smiley: 

@prokopyl [(original post)](https://github.com/RustAudio/rust-lv2/pull/16#issuecomment-529208141)

> > I generally like the idea of the `URIDBound` since it makes generic methods with URIDs easier to write. For example:
> > 
> > ```rust
> > fn write_urid<T: URIDBound>(target: &mut u32, cache: &T::CacheType) {
> >     *target = T::urid(cache).get();
> > }
> > ```
> > 
> > This is very handy indeed!
> > 
> 
> Maybe I missed something, but users would have to use it that way, right? (assuming `test_urids` is an instance of `TestURIDs` here)
> 
> ```rust
> write_urid::<Float>(&mut buf, &test_urids.atom);
> ```
> 
> … instead of:
> 
> ```rust
> write_urid::<Float>(&mut buf, &test_urids);
> ```
> Which would be what the user would have to do in the version that uses `URIDCacheMapping`s. (See my archived experiment).
> Implementation would look like this instead:
> 
> ```rust
> fn write_urid<T: UriBound>(target: &mut u32, cache: &impl URIDCacheMapping<T>) {
>     *target = cache.get_urid().get();
> }
> ```
> 
> As you can see, in your version the user has to do the "dispatch" manually still, which can become very cumbersome in more complex scenarios.
> 
> An example is Atom Sequences, which need 2 different URIDs on creation: one for the sequence itself, and one for the unit of the event timestamp, so using `URIDBound` would they have to be written like so?:
> 
> ```rust
> let seq = write_sequence(&mut buffer, &test_urids.cache, &test_urids.unit);
> ```
[...]
> > Also, using pre-defined URID caches does not conflict with having user-defined caches, it even supports them! Take a look at the setting for the literal test:
> > 
> > ```rust
> > struct German;
> > 
> > unsafe impl UriBound for German {
> >     const URI: &'static [u8] = b"http://lexvo.org/id/iso639-1/de\0";
> > }
> > 
> > #[derive(URIDCache)]
> > pub struct TestURIDs {
> >     atom: AtomURIDCache,
> >     german: URID<German>,
> > }
> > ```
> > 
> > Here, we have a case where a URID cache is needed that contains both the URIDs for the atom library and other, custom URIDs. We can simply include that pre-defined cache in our own cache and use it! We don't have to care which URIDs are included or have to update our cache every time a new update for the library comes in.
> > 
> > I guess you thought that specifying a pre-defined URID cache for a URI bound would require a user to always use this specific cache, but as you can see it doesn't! smiley
> 
> I was thinking about trying to do something like this:
> 
> ```rust
> #[derive(URIDCache)]
> pub struct TestURIDs {
>     long: URID<atom::Long>, // A custom cache for a non-custom type
>     german: URID<German>,
> }
> 
> write_urid::<Long>(&mut buf, &test_urids); // Doesn't work! The associated cache type is AtomURIDCache
> 
> write_urid::<German>(&mut buf, &test_urids); // Doesn't work either actually?
> ```
> 
> This is useful in case the plugin author wants only a subset of a spec's provided URID-bound items (which, in case of the `unit` spec for example, is quite a lot), but this is impossible here, because the `Long` type is tied to the `AtomURIDCache`, so it's the only one that can be passed, and never a custom one.
> 
> Also, in your example where you add the `German` type, wouldn't it also have to implement `URIDBound`, and have a specified cache type to work with `write_urid` as well?

**Comment by Janonard** [comment]
In most cases, something like `URIDCacheMapping` would be the most elegant solution. However, there you run into some problems if you try

**Comment by Janonard** [comment]
I agree that `URIDCacheMapping` is the most elegant solution in most cases; At first I thought about it too. However, I was not able to implement a procedural macro that implements `URIDCacheMapping` for every URID contained in every sub-cache of a `URIDCache` yet. I also think that this should not be left to the users to do. Therefore, I've chosen the second-best option, which is at least better than passing every URID around by hand. If you come up with an elegant derive macro, we should use that instead.

**Comment by prokopyl** [comment]
Good call on moving this conversation! I also felt this was getting a little bit out of hand, myself. :slightly_smiling_face: 

I should be able to send a PR your way with the changes this weekend!

**Comment by Janonard** [comment]
This discussion is a bit out of date now since a different, but still practical, canonical style of URID handling has emerged. If you have a new suggestion for URID handling, please open a new Issue!
