### ISSUE TITLE
Does Plugin need to be Sync?

### ISSUE THREAD

**Issue by niclashoyer** [RustAudio/rust-lv2#30]
I'm trying to port a somewhat more complex plugin to lv2 that currently requires `Cell` at some point, which is not `Sync`. If I change the `Cell` to something like an atomic type or use `RwLock`, it works, but I'm trying to avoid that in the audio path.

Given the [lv2 threading rules](http://lv2plug.in/ns/lv2core/), which state:

> When any function is running for a plugin instance, no other function in the same class may run for that instance.

it seems that Sync may not be necessary?

**Comment by Janonard** [comment]
There's one small detail:

> no ther function **in the same class** may run for that instance.

This means that, for example, the `run` method may not be run twice concurrently on the same plugin instance. However, methods from other classes may. Take a look at the [`save` method from the state specification](https://lv2plug.in/doc/html/group__state.html#a38d316ee6d5ca20b1666a31ab94dc294). It runs in its own threading class and the documentation explicitly states that it may be called concurrently with methods from the "Audio" threading class, for example `run`.

This means that the host may execute a plugin's `run` method and store it's state at the same time. This requires the plugin to be `Sync`, I'm sorry :confused:

**Comment by niclashoyer** [comment]
Thank you for pointing me in the right direction! I think that this is a very bad design decision by LV2, but as you said, it actually states this explicitly:

> This function has its own special threading class: [...] it may be called concurrently with an "Audio" function. The plugin is responsible for any locking or lock-free techniques necessary to make this possible.

> Plugins that dynamically modify state while running, however, must take care to do so in such a way that a concurrent call to save() will save a consistent representation of plugin state for a single instant in time.

Which is actually `Sync`.

If anyone finds this in the future: I solved my `Cell` problems by using a [`crossbeam::AtomicCell`](https://docs.rs/crossbeam/*/crossbeam/atomic/struct.AtomicCell.html) instead.
