### ISSUE TITLE
How to get host feature ?

### ISSUE THREAD

**Issue by YruamaLairba** [RustAudio/rust-lv2#33]
Hello, i'm trying to do some draft for the worker feature and i'm stuck at a early step where i'm trying to determine if the host provide provide the feature. As i understood, the rust-lv2 have already infrastructure to deal with feature, but i can't understand what traits i need to implement and what functions to call in `new()` to get the feature.

I tried to implement my own marker feature like 'IsLIve' or 'HardRTCapable' and then, in the new() function, i tried to use `features.map.map_type::<MyUriBound>()` but it always return an Urid, even when the Uri of my UriBound doesn't correspond to any spec.

**Comment by Janonard** [comment]
Okay, there are two different questions here: 1) How do you retrieve a host feature as a plugin and 2) How do you implement new host features.

1) This is mostly done by the `PluginInstance`, which provides the raw interface for the host. You specify the required features by creating a struct (containing other structs which implement `Feature`),  deriving `FeatureCollection` for it and setting it as the `Features` type of your plugin. When the host instantiates the plugin, the plugin instance will try to fill this struct. If a feature is missing, the feature collection can not be created and the plugin instantiation fails. An example for that is  `midigate/src/lib.rs` in [the book](https://janonard.github.io/rust-lv2-book/). You can also use optional features, which are features that are wrapped in an `Option`. This would look like this:
``` Rust
#[derive(FeatureCollection)]
pub struct Features<'a> {
    map: Option<Map<'a>>,
}
```
If the host doesn't supply this feature, the corresponding field is set to `None`.

2) You implement the `Feature` trait for it. There are a number of different examples in the source code, please take a look at them first.

**Comment by YruamaLairba** [comment]
Thank you, i think i had understood most of main lines. At a time was confused because i was mistake Map with std::Map so i wasn't unable to understand what Features contain. I will try soon to make an host run a worker thread
