### ISSUE TITLE
Worker Specification

### ISSUE THREAD

**Issue by Janonard** [RustAudio/rust-lv2#35]
As decided, we still need the worker specification for the upcoming, first release.

This specification introduces a plugin extension and a host feature. Using the worker feature, a plugin can schedule asynchronous, non-real-time work in the `run` method, which will be completed before `run` is called the next time.

The work itself is done by a `work` method introduced by the worker extension. The communication between the `run` method and the `work` method is done by sending POD, which offers a place to apply the Atom system too.

**Comment by Janonard** [comment]
I've moved this feature to the next release since I want to make sure that the release still happens in March before my next lectures start.

**Comment by YruamaLairba** [comment]
I Just see this is enhancement issue. I'm working on the worker spec since almost 2 week now, and what i did is already usable. I thinks there only some details to solve to make it really clean and coherent.

**Comment by Janonard** [comment]
Sure, I'm looking forward to your pull request!

**Comment by YruamaLairba** [comment]
Hi, I published an example of using the worker spec https://github.com/YruamaLairba/rust-lv2-more-examples. 

What works remain:
- Some documentations is missing, especially example 
- Need to check if some unsound stuff remain. For example, I have a big doubt about a marginal use of ScheduleHandler. (help needed)
- Coding style improvement: should i make module ? Is my naming convention coherent ? (help needed for example:
  - i needed to add an accessor to Pluginstance but the name may not indicate for what it's used
  - i want to handle better the optional end_run function. The current choice is to give a default implementation that does nothing and always give the corresponding callback to the host. I think it's better to give a null pointer when end_run is not used. Should I use #[cfg(feature=..)] or macro or something else ?
 - prepare for merging: should i plan to merge on master or develop ? (my current work is build on top of master)

**Comment by Janonard** [comment]
Please, create a fork of the project, make your changes there and create a PR.  Otherwise, I can not work with your changes!

**Comment by YruamaLairba** [comment]
pull request done. I have a big issue since i updated the different Cargo.toml, i'm unable to use cargo check so my linter now doesn't work ;(

**Comment by YruamaLairba** [comment]
Just a comment to signal i have found a multithread unsound issue in what i did. The current implementation allow uncontrolled concurrent write access of the plugin data. It's possible to enforce plugin implementor to use mutex like protections by changing all mutable borrow of plugin by non-mutable borrow in plugin and worker trait. I think we should to find a way to have this enforcement enabled by default when using worker spec while giving an explicit way to say "that field doesn't require mutex"
