### ISSUE TITLE
Could not compile 'lv2-core-derive'

### ISSUE THREAD

**Issue by DanJCraig** [RustAudio/rust-lv2#90]
Trying to build the amp example, but cargo is failing to compile lv2-core-derive (I have never used rust-lv2 before so its a fresh download). I get 2 errors 
`error[E0432]: unresolved import `syn::export`
 -->path_to/registry/src/github.com-1285ae84e5963aae/lv2-core-derive-2.1.0/src/feature_collection_derive.rs:2:10
  |
2 | use syn::export::Span;
  |          ^^^^^^ could not find `export` in `syn`

`error[E0432]: unresolved import `syn::export`
 --> path_to/registry/src/github.com-1285ae84e5963aae/lv2-core-derive-2.1.0/src/port_collection_derive.rs:2:10
  |
2 | use syn::export::Span;
  |          ^^^^^^ could not find `export` in `syn`

`error: aborting due to 2 previous errors
For more information about this error, try `rustc --explain E0432`.
error: could not compile `lv2-core-derive`

A quick search suggests that this issue is not unique to 'rust-lv2':
https://github.com/nushell/nushell/issues/2867

**Comment by Janonard** [comment]
Was able to reproduce the error. Syn doesn't export the `Span` type anymore, which means that it needs to be imported from proc_macro2 directly. I'm trying to publish a fix as soon as possible.

**Comment by Janonard** [comment]
Fixed and [published](https://crates.io/crates/lv2-core-derive).
