### ISSUE TITLE
LV2 log output

### ISSUE THREAD

**Issue by Philipp91** [RustAudio/rust-lv2#91]
Is there already a Rust binding for the [logging functions](https://lv2plug.in/doc/html/group__logger.html) like `lv2_log_error()`?

If so, sorry I couldn't find it, I'm happy to improve the documentation in the places I looked. If not, consider this a feature request.

**Comment by Janonard** [comment]
Unfortunately, the logging spec is not implemented. You would need to implement it yourself as I neither have the time to implement it nor to administer it's integration.
