### ISSUE TITLE
Resignation as Maintainer

### ISSUE THREAD

**Issue by Janonard** [RustAudio/rust-lv2#97]
Hello!

I've tried this before, but I think I need to do it again: I would like to resign as a maintainer of Rust-LV2.

It's been a blast working on this project with you and I appreciate what we've done together, but I have to admit that I have to move on. For once, I'm still very busy with my studies, but I'm also active in my student's council now and started to work as a C++ programmer. I just don't have the time to review pull requests and moderate discussions anymore. From my point of view, this is not only a drag for the project, but also potentially dangerous: Since I'm not an active Rust programmer anymore, I may therefore miss a lot errors and opportunities.

I'm glad that you are back @prokopyl and your PR #93 and the new tags are pieces of very good work, and I trust that you will continue do great stuff. May I therefore ask you to take my responsibilities? Since you're already part of the maintainers group, this would only mean that I will transfer the Rust crates to you, and then I will leave the group of maintainers. Is this okay for you?

**Comment by prokopyl** [comment]
Well, _technically_ I didn't really resign from my responsibilities as a maintainer (even though I had to leave for a while for personal reasons), so I absolutely don't mind taking your responsibilities. :slightly_smiling_face: 

I'll send you an email soon to discuss the technicalities of the crates.io ownership transfer. ^^

Although I am fine with coming back as a maintainer, I also want to have a co-maintainer available in case I need to be away for a few days or weeks again (plus, having some peer review always helps a lot), so I probably should start looking around here! :wink:

**Comment by PieterPenninckx** [comment]
> I also want to have a co-maintainer available in case I need to be away for a few days or weeks again (plus, having some peer review always helps a lot)

You can always ping me for a review.

**Comment by prokopyl** [comment]
> You can always ping me for a review.

Sure! Although, feel also free to comment on/review my PRs even if I haven't explicitely mentioned you, IMO the more reviews there are around, the better :slightly_smiling_face:

**Comment by Janonard** [comment]
Thank you @prokopyl and @PieterPenninckx! I'm glad to have this sorted out!
